# -*- coding: utf-8 -*-
"""Group 8: Project: Classes

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GpCg_3aIBqy75dRBfZxlM941-ZVN5iv3
"""

class Management:
    #Constructor
    def __init__(self):
        self.doctor_manager = DoctorManager()
        self.patient_manager = PatientManager()

    def displayMenu(self):
        while True:
            print("\nWelcome to Alberta Hospital (AH) Management system")
            print("Select from the following options, or select 3 to stop:")
            print("1 -  Doctors")
            print("2 -  Patients")
            print("3 -  Exit Program")
            choice = input(">>> ") # Mutiple print to make it easier to read

            if choice == "1":
                self.doctorsMenu() # refers to the method in DoctorManager
            elif choice == "2":
                self.patientsMenu() # refers to the method in PatientrManager
            elif choice == "3": # Exits
                print("Thanks for using the program. Bye!")
                break
            else: #Re-enters the loop
                print("Invalid option, please try again.")

    def doctorsMenu(self):
        while True:
            print("\nDoctors Menu:")
            print("1 - Display Doctors list")
            print("2 - Search for doctor by ID")
            print("3 - Search for doctor by name")
            print("4 - Add doctor")
            print("5 - Edit doctor info")
            print("6 - Back to the Main Menu")
            choice = input(">>> ") #Mutiple print to make it easier to read

            if choice == "1":
                self.doctor_manager.displayDoctorsList()#refers to the method in DoctorManager
            elif choice == "2":
                self.doctor_manager.searchDoctorById()#refers to the method in DoctorManager
            elif choice == "3":
                self.doctor_manager.searchDoctorByName()#refers to the method in DoctorManager
            elif choice == "4":
                self.doctor_manager.addDrToFile()#refers to the method in DoctorManager
            elif choice == "5":
                self.doctor_manager.editDoctorInfo()#refers to the method in DoctorManager
            elif choice == "6":
                break
            else:
                print("Invalid option, please try again.")

    def patientsMenu(self):
        while True:
            print("\nPatients Menu:")
            print("1 - Display patients list")
            print("2 - Search for patient by ID")
            print("3 - Add patient")
            print("4 - Edit patient info")
            print("5 - Back to the Main Menu")
            choice = input(">>> ")

            if choice == "1":
                self.patient_manager.display_patients_list()
            elif choice == "2":
                self.patient_manager.search_patient_by_Id()
            elif choice == "3":
                self.patient_manager.add_patient_to_file()
            elif choice == "4":
                self.patient_manager.edit_patient_info_by_id()
            elif choice == "5":
                break
            else:
                print("Invalid option, please try again.")

#Main
hospital_management = Management()
hospital_management.displayMenu()